const componentTemplate = (filename: string): string => {
  return `
//  Generated by relay-snapshot-test-generator 
import React from 'react';
//  TODO: replace with real component
import ${filename} from './../${filename}';
import {createMockEnvironment, MockPayloadGenerator} from 'relay-test-utils';
import ReactTestRenderer from 'react-test-renderer';
import {QueryRenderer, graphql} from 'react-relay';


test('${filename} Render State', () => {
  const environment = createMockEnvironment();
  const renderer = ReactTestRenderer.create(
    <${filename} environment={environment} />,
  );
  environment.mock.resolveMostRecentOperation(operation =>
    MockPayloadGenerator.generate(operation),
  );
  expect(renderer).toMatchSnapshot();
});`;
};

export default componentTemplate;
